<?php
// Variables
return [
  'creatorName' => env('APP_NAME'),
  'creatorUrl' => env('APP_URL'),
  'templateName' => env('APP_NAME'),
  'templateSuffix' => 'Dashboard',
  'templateVersion' => '1.0.0',
  'templateFree' => false,
  'templateDescription' => 'Aljanah Express Cargo System',
  'templateKeyword' => 'Aljanah, Cargo, Express, Tracking, Shipment, fast, libya, turkey',
  'licenseUrl' => env('APP_URL'),
  'livePreview' => env('APP_URL'),
  'productPage' => env('APP_URL'),
  'support' => env('APP_URL'),
  'moreThemes' => env('APP_URL'),
  'documentation' => env('APP_URL'),
  'generator' => '',
  'changelog' => env('APP_URL'),
  'repository' => env('APP_URL'),
  'gitRepo' => '',
  'gitRepoAccess' => '',
  'githubFreeUrl' => env('APP_URL'),
  'facebookUrl' => env('APP_URL'),
  'twitterUrl' => env('APP_URL'),
  'githubUrl' => env('APP_URL'),
  'dribbbleUrl' => env('APP_URL'),
  'instagramUrl' => env('APP_URL'),
  'loginSideBackground' => env('LOGIN_SIDE_BACKGROUND'),
];