<?php
// Variables
return [
  'creatorName' => 'Alajanh',
  'creatorUrl' => 'https://janahx.com',
  'templateName' => 'ALJANAH',
  'templateSuffix' => 'Dashboard',
  'templateVersion' => '1.0.0',
  'templateFree' => false,
  'templateDescription' => 'Aljanah Express Cargo System',
  'templateKeyword' => 'Aljanah, Cargo, Express, Tracking, Shipment, fast, libya, turkey',
  'licenseUrl' => 'https://janahx.com',
  'livePreview' => 'https://janahx.com',
  'productPage' => 'https://janahx.com',
  'support' => 'https://janahx.com',
  'moreThemes' => 'https://janahx.com',
  'documentation' => 'hhttps://janahx.com',
  'generator' => '',
  'changelog' => 'https://janahx.com',
  'repository' => 'https://janahx.com',
  'gitRepo' => 'janahx',
  'gitRepoAccess' => 'janahx',
  'githubFreeUrl' => 'https://janahx.com',
  'facebookUrl' => 'https://www.facebook.com/janahcargo',
  'twitterUrl' => 'https://janahx.com',
  'githubUrl' => 'https://janahx.com',
  'dribbbleUrl' => 'https://janahx.com',
  'instagramUrl' => 'https://janahx.com',
];