name: FTP Deploy

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  ftp-deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup FTP Deploy Action
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        
    - name: Send Notification Email
      uses: mxschmitt/action-tmate@v4
      with:
        smtp_server: ${{ secrets.SMTP_SERVER }}
        smtp_port: 465
        smtp_username: ${{ secrets.SMTP_USERNAME }}
        smtp_password: ${{ secrets.SMTP_PASSWORD }}
        to_email: m.nahaisi96@gmail.com
        from_email: ${{ secrets.SMTP_USERNAME }}
        subject: 'Deployment Successful'
        body: 'Your deployment to FTP was successful.'   

   
