name: FTP Deploy

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  ftp-deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup FTP Deploy Action
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

      - name: Send Notification Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          to: m.nahaisi96@gmail.com
          from: 'Al-Janah'
          subject: 'Deployment Successful'
          body: 'Your deployment to FTP was successful.'
