name: FTP Deploy

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  ftp-deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: FTP Deploy Action
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: githubaccount@aljanahtransport.com
        password: ${{ secrets.FTP_PASSWORD }}
