name: FTP Deploy

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  ftp-deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup FTP Deploy Action
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
