name: FTP Deploy

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  ftp-deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup FTP Deploy Action
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}

    - name: Send Notification Email
      env:
        SMTP_SERVER: smtp.example.com
        SMTP_PORT: 465
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        TO_EMAIL: m.nahaisi96@gmail.com
      run: |
        echo "Subject: Deployment Successful" | sendmail -S $SMTP_SERVER:$SMTP_PORT -au$SMTP_USERNAME -ap$SMTP_PASSWORD $TO_EMAIL   
