name: FTP Deploy
on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  ftp-deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: FTP Deploy Action
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./your-local-directory # Optional: specify a directory to deploy if not root
        git-ftp-args: --insecure # Optional: add additional flags
